[package]
name = "glsp-proc-macros"
version = "0.1.0"
authors = []
publish = false
edition = "2018"

[lib]
proc-macro = true

[dependencies]
glsp = { package = "glsp-engine", path = "../glsp-engine", version = "0.*" }
